# Generated by Django 5.0.7 on 2024-08-18 16:55

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='image_path',
        ),
        migrations.AddField(
            model_name='container',
            name='image_input',
            field=models.ImageField(default='', upload_to=crud.models.upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='image_output',
            field=models.ImageField(default=' ', upload_to=crud.models.upload_path),
            preserve_default=False,
        ),
    ]
