# Generated by Django 5.0.7 on 2024-08-25 14:07

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_container_image_path_container_image_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='code',
            field=models.CharField(default='AJSJ', max_length=255),
        ),
        migrations.AlterField(
            model_name='container',
            name='detection_threshold',
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name='container',
            name='image_output',
            field=models.ImageField(blank=True, upload_to=crud.models.upload_path),
        ),
    ]
